# 
control_dt: 0.02

msg_type: "hg"     # "hg" or "go"
imu_type: "torso"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

# policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/h1_2/motion.pt"
policy_path: "{LEGGED_GYM_ROOT_DIR}/imported_policies/policy.pt"

leg_joint2motor_idx: [0, 1, 2, 3, 4, 5, 
                      6, 7, 8, 9, 10, 11]

arm_waist_joint2motor_idx: [12, 
                            13, 14, 15, 16, 17, 18, 19,
                            20, 21, 22, 23, 24, 25, 26]

joint2motor_idx: [0, 1, 2, 3, 4, 5, 
                  6, 7, 8, 9, 10, 11,
                  12, 
                  13, 14, 15, 16, 17, 18, 19,
                  20, 21, 22, 23, 24, 25, 26]

kps: [60, 60, 60, 80, 60, 0, 
      60, 60, 60, 80, 60, 0,
      160,
      60, 60, 60, 30, 30, 15, 15,
      60, 60, 60, 30, 30, 15, 15]

kds: [4.0, 4.0, 4.0, 4.0, 5, 5,  
      4.0, 4.0, 4.0, 4.0, 5, 5,
      3.0,
      2.5, 5.0, 5.0, 1.0, 1.0, 1.0, 1.0,
      2.5, 5.0, 5.0, 1.0, 1.0, 1.0, 1.0]

default_angles: [0, -0.135, 0.0, 0.2, 0.15, 0.0, 
                 0, -0.135, 0.0, 0.2, 0.15, 0.0,
                 0,
                 0, 0.2, 0, 1.5, 0, 0, 0,
                 0, -0.2, 0, 1.5, 0, 0, 0]

ang_vel_scale: 1.0
dof_pos_scale: 1.0
dof_vel_scale: 1.0
action_scale: 0.5
cmd_scale: [2.0, 2.0, 1.0]
num_actions: 27
num_obs: 92

max_cmd: [0.8, 0.5, 1.57]
